### ISSUE TITLE
Unity Render Streaming/WebRTC Compatibility?

### ISSUE THREAD

**Issue by atx-barnes** [keijiro/Rcam2x#1]
Hello, I've been playing around with Bibcam/Rcam recently with Unity Render Streaming trying to send the packed frame that the Bibcam encoder generates to another client for demuxing into a point cloud. Is there a reason why this wouldn't work with Unity's Render Streaming package? Is there a graphics format or limitation issue with how Unity's package works over using NDI?

Thanks

**Comment by keijiro** [comment]
NDI supports per-frame metadata -- You can embed generic XML data into each frame. I used it to embed camera parameters into frames.

I've never used Unity Render Streaming but hardly think it supports something like that.

In Bibcam, I used barcode to embed the data into each frame. You might be able to use the same approach in Unity Render Streaming/WebRTC.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problems.
